pokemon_inventory/__init__.py
from flask import Flask
from .site.routes import site
from config import Config
from .authentication.routes import auth
from .api.routes import api


app = Flask(__name__)

app.register_blueprint(site)
app.register_blueprint(auth)
app.register_blueprint(api)
app.config.from_object(Config)

pokemon_inventory/api/routes.py
from flask import Blueprint

api = Blueprint('api', __name__, url_prefix = '/api')

@api.route('/getdata')

def getdata():
    return{'some':'value'}

pokemon_inventory/authentication/routes.py
from flask import Blueprint, render_template

auth = Blueprint('auth', __name__, template_folder = 'auth_templates')

@auth.route('/signup', methods = ['GET', 'POST'])
def signup():
    return render_template('signup.html')

@auth.route('/signin', methods = ['GET', 'POST'])
def signin():
    return render_template('signin.html')

pokemon_inventory/site/routes.py
from flask import Blueprint, render_template

site = Blueprint('site', __name__, template_folder = 'site_templates')

@site.route('/')
def home():
    return render_template('index.html')

@site.route('/profile')
def profile():
    return render_template('profile.html')

@site.route('/Donate')
def Donate():
    return render_template('Donate.html')

pokemon_inventory/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="../static/css/main.css">
<title>Title</title>
</head>
<body>
    <nav class="ct-nav bg-danger">
        <div>
            <img src="../static/Images/icon-1.png" alt="">
        </div>


    <div>
        <ul id="horizontal-list">
            <a href="{{ url_for('site.home')}}">
                <li class="text-warning">Pokemon Collector Project</li>
            </a>
            <a href="{{ url_for('site.profile') }}">
                <li class ="text-warning">Profile</li>
            </a>
            <a href="{{ url_for('site.Donate') }}">
                <li class="text-warning">Donate</li>
            </a>
            <a href="{{ url_for('auth.signin') }}">
                <li class="text-warning">Sign-In</li>
            </a>
            <a href="{{ url_for('auth.signup') }}">
                <li class="text-warning">Sign-up</li>
            </a>
        </ul>
    </div>
    </nav>
    {% block content %}

    {% endblock content %}

<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.9.2/umd/popper.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.1.0/js/bootstrap.min.js"></script>
</body>
</html>